// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhomqbfeepbxxgwnmgaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRob21xYmZlZXBieHhnd25tZ2F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTU1MjIsImV4cCI6MjA3MDMzMTUyMn0.pJNOhsaVJMvJvdskUBRCBG9ZYQMmSdFU6wQiiXln3iQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});